[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "excelstyleskit"
version = "2.0"
description = "A lightweight utility for programmatically styling Excel spreadsheets."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Angyee Marin", email = "angyeemarin.dev@gmail.com" }
]
keywords = ["excel", "styles", "openpyxl", "xlsx", "design", "colors"]
dependencies = [
    "et-xmlfile>=1.1.0",
    "openpyxl>=3.1.5",
]
urls = { Homepage = "https://github.com/xanv754/ExcelStylesKit" }

[tool.setuptools]
packages = ["excelstyleskit"]
